### PR TITLE
Bug 1795693: change the next empty encryption key's name for encryption e2e test

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
quite big, not sure how can I make it smaller (update only library-go)

**Comment by tnozicka** [comment]
> quite big, not sure how can I make it smaller (update only library-go)
you can bump only library-go (+transitives) with `go get -u github.com/openshift/library-go@master`

**Comment by mfojtik** [comment]
@tnozicka i tried to switch to go.mod but @sttts stopped me (we don't really want to take any risks in this branch)

**Comment by tnozicka** [comment]
It is fine, I like safe for backports. I was mentioning it only because it made my previous comment irrelevant.

**Pull request merged**
