### PR TITLE
API-1835: update library-go to use new operator client

### PR DESCRIPTION
**Pull request by deads2k**
from https://github.com/openshift/library-go/pull/1787

### CODE REVIEW

**Comment by deads2k** [comment]
Yep. We'll need to change the schema to accommodate this

```
PREVIOUS_DESIRED: {
  "conditions": [
    {
      "type": "APIServerStaticResourcesDegraded",
      "status": "False",
      "reason": "AsExpected"
    }
  ]
}
 DESIRED: {
  "conditions": [
    {
      "type": "APIServerStaticResourcesDegraded",
      "status": "False",
      "reason": "AsExpected",
      "message": ""
    }
  ]
}
```

**Comment by deads2k** [comment]
Hmmm, or update our notion of equality. Probably a case for each

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
