### PR TITLE
manifests: move role and rolebinding needed by prometheus servicemonitor

### PR DESCRIPTION
**Pull request by paulfantom**
We forgot to move Role and RoleBinding when moving ServiceMonitor out of cluster monitoring operator.

Follow-up to https://github.com/openshift/cluster-openshift-apiserver-operator/pull/208

Relates to https://github.com/openshift/cluster-monitoring-operator/pull/438

/cc @s-urbaniak

### CODE REVIEW

**Comment by paulfantom** [comment]
ping @openshift/openshift-team-master-maintainers

**Comment by deads2k** [comment]
since these are in the managed namespace, they should be managed by our operator, not the CVO.

@sanchezl please guide them to the right spot.

**Comment by sanchezl** [comment]
@paulfantom 
1. Add files to [bindata](https://github.com/openshift/cluster-openshift-apiserver-operator/tree/master/bindata/v3.11.0/openshift-apiserver)
2. Apply files in the the [workload controller](https://github.com/openshift/cluster-openshift-apiserver-operator/blob/71872cd0505a5357e28928bf029422477857d3d1/pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go#L48).

**Comment by s-urbaniak** [comment]
ping @paulfantom re: https://github.com/openshift/cluster-openshift-apiserver-operator/pull/224#issuecomment-523053192

**Comment by s-urbaniak** [comment]
@paulfantom ping, can you please verify if this is still relevant?

**Pull request closed without merging**
