### PR TITLE
bindata: monitor openshift-apiserver namespace

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @sttts @deads2k @brancz @paulfantom

### CODE REVIEW

**Comment by s-urbaniak** [comment]
ping @soltysh @sttts for an approval :pray:

**Comment by s-urbaniak** [comment]
ping @soltysh @p0lyn0mial @sttts

**Comment by p0lyn0mial** [comment]
will find someone that can approve this PR :)
@mfojtik could you have a look?

**Comment by s-urbaniak** [comment]
@p0lyn0mial thank you :+1: could you also pull in https://github.com/openshift/cluster-openshift-apiserver-operator/pull/208 ?

**Pull request merged**
