### PR TITLE
encryption: switch to kube-storage-version-migrator

### PR DESCRIPTION
**Pull request by vareti**
continuing the work done in #245 

Requires https://github.com/openshift/cluster-kube-storage-version-migrator-operator to be in the release.

### CODE REVIEW

**Comment by marun** [comment]
@vareti The failure of the e2e-aws-operator-encryption-perf doesn't appear to be infrastructure related. Is the job flakey, or is it ligit failing?

**Comment by vareti** [comment]
@marun it does not look like a infra failure. looks like a timeout from the test logs. and there is not much info in the migrator logs to check what went wrong. i am running this again to see it is flaky

**Comment by vareti** [comment]
@marun So looks like test is indeed flaky. I tried running the same test locally on my machine and it passed there too.

**Comment by marun** [comment]
Hooray, passed!

**Pull request merged**
