### PR TITLE
bump(*): library-go for fileobserver fixes and switch to go.mod

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
/override ci/prow/verify-deps

I will get this removed soon

**Comment by mfojtik** [comment]
verify-deps removal: https://github.com/openshift/release/pull/5887

**Comment by mfojtik** [comment]
flake: https://bugzilla.redhat.com/show_bug.cgi?id=1772189

/retest

**Comment by deads2k** [comment]
all about some glide, eh?

/approve

**Comment by mfojtik** [comment]
@soltysh ```
fail [github.com/openshift/origin/test/extended/cli/explain.go:341]: Unexpected error:
    <*errors.errorString | 0xc004852960>: {
        s: "oc explain [\"openshiftapiservers\" \"--api-version=operator.openshift.io/v1\"] result {KIND:     OpenShiftAPIServer\nVERSION:  operator.openshift.io/v1\n\nDESCRIPTION:\n     <empty>} doesn't match pattern {(?s)DESCRIPTION:.*FIELDS:.*spec.*<.*>.*(status.*<.*>.*)?}",
    }
    oc explain ["openshiftapiservers" "--api-version=operator.openshift.io/v1"] result {KIND:     OpenShiftAPIServer
    VERSION:  operator.openshift.io/v1
    
    DESCRIPTION:
         <empty>} doesn't match pattern {(?s)DESCRIPTION:.*FIELDS:.*spec.*<.*>.*(status.*<.*>.*)?}
occurred
```

this is failing pretty consistently in this PR, any clues?

**Pull request merged**
