### PR TITLE
Quickfix: increase pod readiness timeout

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by mfojtik** [comment]
/lgtm

@sttts can we have issue to investigate why is this needed?

**Comment by sttts** [comment]
Here is a log with infinite readiness failureThreshold: https://gist.github.com/sttts/044eeb31338731f9c639d90bf6759980

**Comment by deads2k** [comment]
> Works for me (on libvirt).

alright.  I'll assume CI is borked and this will unstick us.  @sttts keep an eye out to see if this helps or destroys us.

**Comment by stlaz** [comment]
Actually, it seems that it makes the pod survive the first hour, but after that, it's crash-looping again.

**Comment by sttts** [comment]
> Actually, it seems that it makes the pod survive the first hour, but after that, it's crash-looping again.

Citing @stlaz from Slack: 

> ah, damn, I'm on a wrong VM -.-

**Pull request merged**
