### PR TITLE
OCPBUGS-10568: migrate to using lease objects for leader election

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Review by sanchezl — APPROVED** [review]
/lgtm

**Comment by tkashem** [comment]
master (4.14) is already using `lease` 
https://github.com/openshift/cluster-openshift-apiserver-operator/blob/a606683653adfb6fae143344999e6c4165feadc2/vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go#L63


/close

**Comment by tkashem** [comment]
/close

master (4.14) is already using `lease` 

https://github.com/openshift/cluster-openshift-apiserver-operator/blob/a606683653adfb6fae143344999e6c4165feadc2/vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go#L63

**Pull request closed without merging**
