### PR TITLE
manifests: add servicemonitor for openshift apiserver

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @paulfantom @deads2k @sttts @brancz

/hold

This depends on #207

### CODE REVIEW

**Comment by s-urbaniak** [comment]
another ping @soltysh @sttts for an approval :pray:

**Comment by paulfantom** [comment]
/hold cancel

ping @soltysh @sttts

**Comment by s-urbaniak** [comment]
ping @soltysh @p0lyn0mial @sttts

**Pull request merged**
