### PR TITLE
Revert "Revert "add clusteroperator resource to CVO payload""

### PR DESCRIPTION
**Pull request by deads2k**
Reverts openshift/cluster-openshift-apiserver-operator#91

/hold

lets see what CI says now.

### CODE REVIEW

**Comment by vrutkovs** [comment]
This would flake a lot due to #86

**Comment by deads2k** [comment]
> This would flake a lot due to #86

Just looking for logs (which still appear to be missing).  I think I found it in https://github.com/openshift/cluster-openshift-apiserver-operator/pull/93

**Comment by deads2k** [comment]
not green, but no clusteroperators at all....


/test e2e-aws
--

**Comment by deads2k** [comment]
green

/test e2e-aws

**Comment by mfojtik** [comment]
LGTM (although the `openshift-cluster-openshift-apiserver-operator` looks weird ;-)

**Pull request closed without merging**
