### PR TITLE
update manifest filenames to conform to expected format

### PR DESCRIPTION
**Pull request by juanvallejo**
Updating per https://github.com/openshift/origin/blob/master/pkg/oc/cli/admin/release/new.go#L566
Will update the cluster-openshift-controller-manager-operator as well if this update makes sense

cc @smarterclayton @deads2k

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I think the files should be 0000_<run level>_<operator are>_<>

**Comment by juanvallejo** [comment]
@abhinavdahiya @smarterclayton thanks, updated to include run level

**Comment by juanvallejo** [comment]
cc @rajatchopra

**Comment by smarterclayton** [comment]
Your component should be dash separated, exactly like your repository name.

**Comment by juanvallejo** [comment]
@smarterclayton 
> Your component should be dash separated, exactly like your repository name.

Thanks, done

**Pull request merged**
