### PR TITLE
run operator in parallel with apiserver-operator

### PR DESCRIPTION
**Pull request by deads2k**
Updating the runlevel should run us in parallel with the kube-apiserver

/assign @smarterclayton

### CODE REVIEW

**Comment by deads2k** [comment]
look like aws flakes

/retest

**Comment by deads2k** [comment]
failure

/test e2e-aws

**Comment by deads2k** [comment]
terraform
/test e2e-aws

**Comment by smarterclayton** [comment]
Has suspiciously never passed.

/test e2e-aws

**Comment by deads2k** [comment]
7 failures before today.

**Pull request closed without merging**
